import = [
"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
padding.x = 0
padding.y = 0
# decorations = "Full"
opacity = 0.9
blur = true
option_as_alt = "both"
startup_mode = "Maximized"
dynamic_title = true

[font]
size = 9

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{key = "t", mods = "Control", action = "ToggleMaximized"},
{key = "n", mods = "Control", action = "CreateNewWindow" },
{key = "c", mods = "Control", action = "Copy"},
]



