import = [
"~/.config/alacritty/themes/themes/nord.yaml"
]

[window]
padding.x = 10
padding.y = 10
decorations = "Full"
opacity = 0.9
blur = true
option_as_alt = "both"
startup_mode = "Maximized"
dynamic_title = true

[font]
normal.family = "JetBrains Mono"
size = 10

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{key = "t", mods = "Control", action = "ToggleMaximized"},
{key = "n", mods = "Control", action = "CreateNewWindow" },
{key = "c", mods = "Control", action = "Copy"},
]



